# this_file: src/vttiro/config/templates/testing.yaml
# Testing Configuration Template for vttiro
# This template is optimized for automated testing with mocking and test isolation

config_version: "2.0"
environment: "testing"

# API Configuration for Testing
api:
  # Use mock API keys for testing (never real keys in tests)
  gemini_api_key: "test-gemini-key-123"
  assemblyai_api_key: "test-assemblyai-key-123"
  deepgram_api_key: "test-deepgram-key-123"
  huggingface_token: "test-hf-token-123"
  
  # Fast timeouts for testing
  timeout_seconds: 10
  max_retries: 1
  retry_delay: 0.1
  
  # No rate limiting in tests
  rate_limit_per_minute: 10000
  burst_limit: 1000

# Processing Configuration for Testing
processing:
  # Small chunks for fast tests
  chunk_duration: 30  # 30 seconds
  overlap_duration: 5   # 5 seconds
  max_duration: 300     # 5 minutes max for tests
  sample_rate: 16000
  prefer_integer_seconds: true
  
  # Fast processing for tests
  energy_threshold_percentile: 30
  min_energy_window: 0.5
  
  # Minimal parallel processing for test determinism
  max_workers: 1
  worker_timeout: 30
  enable_gpu: false  # Always use CPU for consistent test results

# Validation Configuration for Testing
validation:
  # Relaxed validation for test flexibility
  strict_mode: false
  validate_on_load: false  # Allow test data without validation
  
  # Permissive file validation for test files
  max_file_size_mb: 100  # Smaller for test files
  allowed_domains: ["*"]  # Allow any domain for testing
  allowed_file_types: [".mp4", ".avi", ".mov", ".mp3", ".wav", ".m4a", ".webm", ".test"]

# Caching Configuration for Testing
caching:
  enabled: false  # Disable caching for test isolation
  
  # Memory cache (disabled for tests)
  memory_cache_size: 0
  memory_ttl_seconds: 0
  
  # Disk cache (use temporary directories)
  disk_cache_enabled: false
  disk_cache_path: "/tmp/vttiro-test-cache"
  disk_cache_size_mb: 10
  disk_ttl_seconds: 60
  

# Monitoring Configuration for Testing
monitoring:
  enabled: true
  
  # Testing-specific logging
  log_level: "DEBUG"
  log_to_file: false  # Log to stdout/stderr for test runners
  log_file_path: "/tmp/vttiro-test.log"
  log_rotation_size_mb: 10
  log_retention_days: 1
  structured_logging: true
  
  # Minimal metrics for testing
  metrics_enabled: false
  metrics_port: 0  # Disable metrics server
  detailed_metrics: false
  
  # No health checks needed in tests
  health_check_enabled: false
  health_check_port: 0

# Security Configuration for Testing
security:
  # Minimal security for testing speed
  encryption_enabled: false
  api_key_validation: false
  rate_limiting_enabled: false
  
  # Permissive CORS for testing
  cors_enabled: true
  cors_origins: ["*"]
  
  # Disable security features that slow down tests
  input_sanitization: false
  path_traversal_protection: false
  audit_logging: false

# Output Configuration for Testing
output:
  default_format: "webvtt"
  max_chars_per_line: 42
  max_lines_per_cue: 2
  max_cue_duration: 7.0
  reading_speed_wpm: 160
  
  # Standard accessibility for testing
  wcag_compliance: "AA"
  include_sound_descriptions: true
  
  # Test output settings (use temporary directories)
  output_directory: "/tmp/vttiro-test-output"
  backup_enabled: false

# AI Model Configuration for Testing
models:
  # Use mock providers for testing
  default_provider: "mock"
  fallback_providers: ["mock"]
  
  # Disable circuit breaker for deterministic tests
  circuit_breaker_enabled: false
  failure_threshold: 100
  recovery_timeout: 1
  
  # Mock model settings
  mock:
    model_name: "test-model"
    temperature: 0.0
    enable_streaming: false
    timeout_seconds: 5
    mock_responses: true
  
  # Real model settings (for integration tests)
  gemini:
    model_name: "gemini-2.0-flash-exp"
    temperature: 0.0
    enable_streaming: false
    timeout_seconds: 10
  
  assemblyai:
    model_name: "universal-2"
    enable_diarization: false  # Faster for tests
    enable_punctuation: true
    timeout_seconds: 15
  
  deepgram:
    model_name: "nova-2"
    enable_smart_format: false  # Faster for tests
    enable_profanity_filter: false
    timeout_seconds: 10

# Feature Flags for Testing
features:
  # Enable all features for comprehensive testing
  speaker_diarization: true
  emotion_detection: true
  auto_segmentation: true
  context_aware_prompting: true
  
  # YouTube integration (with mocking)
  youtube_integration: true
  auto_upload_subtitles: false

# Testing-specific settings
testing:
  # Test isolation
  use_temporary_directories: true
  cleanup_after_tests: true
  test_data_directory: "tests/data"
  
  # Mock settings
  mock_api_responses: true
  mock_file_operations: false
  mock_network_requests: true
  
  # Test data
  use_synthetic_audio: true
  synthetic_audio_duration: 10  # seconds
  test_video_urls: [
    "https://example.com/test-video-1.mp4",
    "https://example.com/test-video-2.mp4"
  ]
  
  # Performance testing
  performance_testing: false
  benchmark_iterations: 1
  
  # Integration testing
  integration_testing: false
  real_api_testing: false  # Set to true for API integration tests
  
  # Property-based testing
  property_testing: true
  hypothesis_max_examples: 100
  hypothesis_deadline: 5000  # 5 seconds
  
  # Fixtures and mocks
  fixture_directory: "tests/fixtures"
  mock_responses_directory: "tests/mocks"
  
  # Test database settings
  test_database_url: "sqlite:///:memory:"
  reset_database_per_test: true
  
  # Parallel testing
  parallel_tests: false  # Disable for consistent results
  test_workers: 1

# Test Environment Variables
test_env:
  # Override environment variables for testing
  VTTIRO_ENV: "testing"
  VTTIRO_DEBUG: "true"
  VTTIRO_LOG_LEVEL: "DEBUG"
  PYTHONPATH: "src:tests"
  
  # Test-specific paths
  VTTIRO_CONFIG_PATH: "/tmp/vttiro-test-config"
  VTTIRO_CACHE_PATH: "/tmp/vttiro-test-cache"
  VTTIRO_LOG_PATH: "/tmp/vttiro-test-logs"

# Pytest Configuration
pytest:
  # Test discovery
  testpaths: ["tests"]
  python_files: ["test_*.py", "*_test.py"]
  python_classes: ["Test*"]
  python_functions: ["test_*"]
  
  # Test execution
  addopts: [
    "-v",                    # Verbose output
    "--tb=short",           # Short traceback format
    "--strict-markers",     # Strict marker checking
    "--disable-warnings",   # Disable warnings for cleaner output
    "--color=yes"           # Colored output
  ]
  
  # Markers
  markers: [
    "unit: Unit tests",
    "integration: Integration tests",
    "performance: Performance tests",
    "slow: Slow tests",
    "api: Tests requiring real API calls",
    "gpu: Tests requiring GPU"
  ]
  
  # Coverage
  coverage_enabled: true
  coverage_threshold: 85
  coverage_fail_under: 80